version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run:
          name: check docker version
          command: docker --version

      - run:
          name: build docker image and push to docker hub
          command: |
                TAG=0.1.$CIRCLE_BUILD_NUM
                docker build -t ht_hackathon/client .\client\
                echo $DOCKER_HUB_PW | docker login -u $DOCKER_HUB_USER --password-stdin
                docker push ht_hackathon/client
