version: 2.1
jobs:
  build:
   machine: true
   steps:
     - checkout

     - run:
        name: check docker version
        command: docker --version

     - run:
        name: docker login check with creds
        command: echo "$DOCKER_HUB_PW" | docker login -u $DOCKER_HUB_USER --password-stdin

          
      # - run:
      #     name: build docker image and push to docker hub
      #     command: |
      #       docker build -t ht_hackathon/client .\client\
      #       docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PW
      #       docker push ht_hackathon/client
