version: 2.1
jobs:
  build:
    docker:
      - image: 'circleci/node:4.8.2'
    steps:
      - checkout
      - run:
          name: check docker version
          command: docker --version
      - run:
          name: build docker image and push to docker hub
          command: |
            docker build -t ht_hackathon/client .\client\
            docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PW
            docker push ht_hackathon/client
