version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run:
          name: check docker version
          command: docker --version

      - run:
          name: env variable test
          command: echo $docker_hub_user # should be all capital letters

      - run:
          name: build docker image and push to docker hub
          command: |
                TAG=0.1.$CIRCLE_BUILD_NUM
                docker build -t ht_hackathon/client .\client\
                echo $DOCKER_PASS | docker login -u $docker_hub_user --password-stdin
                docker push ht_hackathon/client
