version: 2.1
jobs:
  build:
   machine: true
   steps:
     - checkout

     - run:
        name: check docker version
        command: docker --version
          
     - run:
        name: build docker image and push to docker hub
        command: |
          ls -a
          # docker build -t ht_hackathon/client .
          # echo "$DOCKER_HUB_PW" | docker login -u $DOCKER_HUB_USER --password-stdin
          # docker push ht_hackathon/client
